In [2]:
import numpy as np
from numpy.matlib import zeros

# Array Creation and Properties

1) ## Create 1D, 2D, and 3D arrays using np.array, np.zeros, np.ones, and np.full.

### 1D Array
why not use pythons own array ?
because numpy gives special functions like say you can do element wise multiplication of numpy array as (a*b) but cant do the same for python arrays

**dattype of all elements in the array would be same**

say you have `np.array([1,2,3.6])` datatype=Float

`np.array([1,2,3.6,"Bilal"])` numpy will convert all the values to datatype string


In [3]:
x=np.array([1,2,3])
y=np.array([4,5,6])

print(x*y)


[ 4 10 18]


In [5]:
ones_1d=np.ones(9,dtype=int)
zeros_1d=np.zeros(9)
full_1d=np.full(9,2)   # shape =1d array of length 9 and 2 is the value to be filled

print("Ones Array ",ones_1d,"\nZeros Array ",zeros_1d,"\nFull Array ",full_1d)

Ones Array  [1 1 1 1 1 1 1 1 1] 
Zeros Array  [0. 0. 0. 0. 0. 0. 0. 0. 0.] 
Full Array  [2 2 2 2 2 2 2 2 2]


### 2D Array

In [7]:
simple_2d=np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

ones_2d=np.ones((3,3),dtype=int)
zeros_2d=np.zeros((4,3))
full_2d=np.full((4,5),2)   # shape =(4 x 5)and 2 is the value to be filled


print("Simple 2D \n",simple_2d,"\nOnes Array \n",ones_2d,"\nZeros Array \n",zeros_2d,"\nFull Array\n",full_2d)

Simple 2D 
 [[1 2 3]
 [4 5 6]
 [7 8 9]] 
Ones Array 
 [[1 1 1]
 [1 1 1]
 [1 1 1]] 
Zeros Array 
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]] 
Full Array
 [[2 2 2 2 2]
 [2 2 2 2 2]
 [2 2 2 2 2]
 [2 2 2 2 2]]


# 3D Array

In [8]:
simple_3d=np.array([          # 2x 2 x3 meaning there are 2 2d arrays of shape(2x3)
    [
        [1,2,3],
        [4,5,6]
    ],

    [
        [7,8,9],
        [10,11,12]
    ],

])

ones_3d=np.ones((2,2,3),dtype=int)
zeros_3d=np.zeros((2,2,3))
full_3d=np.full((2,2,3),2)   # shape =(2 x 2 x 3) and 2 is the value to be filled


print("Simple 3D \n",simple_3d,"\nOnes Array \n",ones_3d,"\nZeros Array \n",zeros_3d,"\nFull Array\n",full_3d)

Simple 2D 
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]] 
Ones Array 
 [[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]] 
Zeros Array 
 [[[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]] 
Full Array
 [[[2 2 2]
  [2 2 2]]

 [[2 2 2]
  [2 2 2]]]


2) ##