In [2]:
import numpy as np
from numpy.ma.core import shape
from numpy.matlib import zeros
from pandas.conftest import axis

# Array Creation and Properties

 ## 1) Create 1D, 2D, and 3D arrays using np.array, np.zeros, np.ones, and np.full.

### 1D Array
why not use pythons own array ?
because numpy gives special functions like say you can do element wise multiplication of numpy array as (a*b) but cant do the same for python arrays

**dattype of all elements in the array would be same**

say you have `np.array([1,2,3.6])` datatype=Float

`np.array([1,2,3.6,"Bilal"])` numpy will convert all the values to datatype string


In [3]:
x=np.array([1,2,3])
y=np.array([4,5,6])

print(x*y)


[ 4 10 18]


In [5]:
ones_1d=np.ones(9,dtype=int)
zeros_1d=np.zeros(9)
full_1d=np.full(9,2)   # shape =1d array of length 9 and 2 is the value to be filled

print("Ones Array ",ones_1d,"\nZeros Array ",zeros_1d,"\nFull Array ",full_1d)

Ones Array  [1 1 1 1 1 1 1 1 1] 
Zeros Array  [0. 0. 0. 0. 0. 0. 0. 0. 0.] 
Full Array  [2 2 2 2 2 2 2 2 2]


### 2D Array

In [7]:
simple_2d=np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

ones_2d=np.ones((3,3),dtype=int)
zeros_2d=np.zeros((4,3))
full_2d=np.full((4,5),2)   # shape =(4 x 5)and 2 is the value to be filled


print("Simple 2D \n",simple_2d,"\nOnes Array \n",ones_2d,"\nZeros Array \n",zeros_2d,"\nFull Array\n",full_2d)

Simple 2D 
 [[1 2 3]
 [4 5 6]
 [7 8 9]] 
Ones Array 
 [[1 1 1]
 [1 1 1]
 [1 1 1]] 
Zeros Array 
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]] 
Full Array
 [[2 2 2 2 2]
 [2 2 2 2 2]
 [2 2 2 2 2]
 [2 2 2 2 2]]


# 3D Array

In [8]:
simple_3d=np.array([          # 2x 2 x3 meaning there are 2 2d arrays of shape(2x3)
    [
        [1,2,3],
        [4,5,6]
    ],

    [
        [7,8,9],
        [10,11,12]
    ],

])

ones_3d=np.ones((2,2,3),dtype=int)
zeros_3d=np.zeros((2,2,3))
full_3d=np.full((2,2,3),2)   # shape =(2 x 2 x 3) and 2 is the value to be filled


print("Simple 3D \n",simple_3d,"\nOnes Array \n",ones_3d,"\nZeros Array \n",zeros_3d,"\nFull Array\n",full_3d)

Simple 2D 
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]] 
Ones Array 
 [[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]] 
Zeros Array 
 [[[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]] 
Full Array
 [[[2 2 2]
  [2 2 2]]

 [[2 2 2]
  [2 2 2]]]


## 2) Use np.arange() and np.linspace() to create arrays with evenly spaced values.

### np.arange()
this functions return an array in range given with the required steps

`np.arange(from,to,step)`

default from is 0
default step is 1

In [11]:
arange_array= np.arange(1,5,dtype=int)

arange_array_2=np.arange(5)

arange_array_3 = np.arange(1,10.1,2) # from 1 to 10 as 10.1 not included with step of 2

print(arange_array)
print(arange_array_2)
print(arange_array_3)

[1 2 3 4]
[0 1 2 3 4]
[1. 3. 5. 7. 9.]


### np.linspace()

used to generate n number of numbers between 2 values in a linear way like difference is same

`np.linspace(from, to, how_many_numbers)`

In [12]:
linspace_usage= np.linspace(1,100,6)
print(linspace_usage)

[  1.   20.8  40.6  60.4  80.2 100. ]


## 3) Check array properties: .ndim, .shape, .size, .dtype.


### ndim
Returns the number of dimensions of the array.

In [15]:
print(simple_2d.ndim)
print(simple_3d.ndim)

2
3


### .shape
returns the shape along with dimensions

In [16]:
print(simple_2d.shape)
print(simple_3d.shape)

(3, 3)
(2, 2, 3)


### .size

return size like a 2x3 has size 6

In [17]:
print(simple_2d.size)
print(simple_3d.size)

9
12


### dtype
returns the data type of the array

In [18]:
print(simple_2d.dtype)
print(simple_3d.dtype)

int64
int64


# Reshape and Flatten

## Reshape arrays using .reshape() and .flatten().

### .reshape()
reshape allow us to reshape our array but while reshaping form less dimension to hogher dimension we need to be careful that the size is similar or else there will be an error

also we can use the syntax `np.reshape(-1,1)` which means 1 column and as many rows as needed or available
`np.reshape(1,-1)`  which means 1 row and as many rows as needed

rather than doing `np.reshape(size,1)`

order="F" means columns wise by default it is row wise

In [23]:
array= np.array([1,2,3,4,5,6,7,8,9,10,11,12])

array_2d=array.reshape((4,3),order="F")

array_3d=array.reshape((2,2,3))

print(array_2d,"\n \n \n 3d \n",array_3d)

[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]] 
 
 
 3d 
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [25]:
single_column= array_3d.reshape((-1,1))
two_column = array_3d.reshape((-1,2))

print(single_column,"\n \n two column\n",two_column)

[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]] 
 
 two column
 [[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]


In [26]:
single_row= array_3d.reshape((1,-1))
two_row = array_3d.reshape((2,-1))

print(single_row,"\n \n two row\n",two_row)


[[ 1  2  3  4  5  6  7  8  9 10 11 12]] 
 
 two row
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


### flatten()
flatten function makes adeep copy meaning like changing the new y variable wont affect the values in original x
and it converts higher dimensional arrays into a 1D array

In [27]:
y1= array_3d.flatten()
y2=array_2d.flatten()

y1[0]=0

print("Original\n",array_3d,"\n \n y1\n \n",y1,"\n \n y2\n \n",y2)

Original
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]] 
 
 y1
 
 [ 0  2  3  4  5  6  7  8  9 10 11 12] 
 
 y2
 
 [ 1  5  9  2  6 10  3  7 11  4  8 12]


# Random Numbers

## Use np.random.randint(), np.random.rand(), np.random.randn(), and np.random.seed() to create random arrays.

### np.random.randint()
return random int numbers between a certain like boundary for a specific shape

In [32]:
random_array = np.random.randint(0, 10, size=(2,3))
print(random_array)

[[0 5 1]
 [8 8 0]]


### np.random.rand()

return random number between 0 and 1 and no negative values

In [37]:
random_array = np.random.rand(2,3)
print(random_array)

[[0.43753955 0.70570874 0.93994972]
 [0.53377796 0.226142   0.74684026]]


### np.random.randn()
return random numbers between0 and 1 also includes negative values

In [38]:
random_array = np.random.randn(2,3)
print(random_array)

[[-0.2468163  -0.56113873  0.46424981]
 [-1.50635365 -0.40897557 -0.74665814]]


### np.random.shuffle()
shuffles the values in place , does not return anything

if you want to return anything use `np.random.permutation(x)`

In [51]:
np.random.shuffle(array_2d)
print(array_2d)

[[ 3  7 11]
 [ 2  6 10]
 [ 1  5  9]
 [ 4  8 12]]


### np.random.seed()
allows us to get the same value while random valuing things as long as we use the same number in the parenthesis of seed

In [61]:
np.random.seed(2)
random_array = np.random.randn(2,3)
print(random_array)

[[-0.41675785 -0.05626683 -2.1361961 ]
 [ 1.64027081 -1.79343559 -0.84174737]]


## Use .mean(), .min(), .max(), .argmin(), .argmax() to summarize data.

## .mean
calculates the mean/average of the data

In [64]:
array=np.array([1,2,3,4,5,6,7])

array2=np.array([
    [1,2,3,4,5],
    [6,7,8,9,10],
    [11,12,13,14,15]
])

mean_1d=np.mean(array)

mean_2d=np.mean(array2)
mean_2d_columns=np.mean(array2,axis=1)

print(mean_1d,"\n",mean_2d,"\n",mean_2d_columns)

4.0 
 8.0 
 [ 3.  8. 13.]


### .min() & .max()
get the minimum and maximum value respectively

In [68]:
array=np.array([1,2,3,4,5,6,7])

array2=np.array([
    [0,2,3,4,5],
    [6,7,8,9,10],
    [11,12,13,14,121]
])

print("Minimum\n",np.min(array),"\n",np.min(array2))
print("Maximum\n",np.max(array),"\n",np.max(array2))

Minimum
 1 
 0
Maximum
 7 
 121


### argmin() & argmax()
returns the indent of the minimum and maximum value

In [69]:
array=np.array([1,2,3,4,5,6,7])

array2=np.array([
    [0,2,3,4,5],
    [6,7,8,9,10],
    [11,12,13,14,121]
])

print("Minimum at index\n",np.argmin(array),"\n",np.argmin(array2))
print("Maximum at index\n",np.argmax(array),"\n",np.argmax(array2))

Minimum at index
 0 
 0
Maximum at index
 6 
 14


#  Indexing and Slicing

## Index and slice 1D and 2D arrays.


### 1D arrays

In [70]:
np.random.seed(0)
array=np.random.randint(1,20,20)

print(array[1:4])
print(array[5:])


[16  1  4]
[ 8 10 19  5  7 13  2  7  8 15 18  6 14  9 10]


### 2D arrays

In [74]:
np.random.seed(0)
array=np.random.randint(1,20,(6,7))

print(array)
print("------------------------------")
print(array[1:4,:])
print("------------------------------")
print(array[5:,3:])

[[13 16  1  4  4  8 10]
 [19  5  7 13  2  7  8]
 [15 18  6 14  9 10 17]
 [ 6 16 16  1 19  4 18]
 [15  8  1  2 10  1 11]
 [ 4 12 19  3  1  1  5]]
------------------------------
[[19  5  7 13  2  7  8]
 [15 18  6 14  9 10 17]
 [ 6 16 16  1 19  4 18]]
------------------------------
[[3 1 1 5]]


### 3D arrays

In [76]:

np.random.seed(0)
array = np.random.randint(1, 20, (2,3,3))

print(array)
print("------------------------------")
print(array[:3, 1,:])
print("------------------------------")


[[[13 16  1]
  [ 4  4  8]
  [10 19  5]]

 [[ 7 13  2]
  [ 7  8 15]
  [18  6 14]]]
------------------------------
[[ 4  4  8]
 [ 7  8 15]]
------------------------------


## Access specific rows, columns, and elements.

`array[::2]` means k 2 sh pehly wali index mtlb index 1 wali cheez nahi chaye baki sb chaye ha

`array[::2,::2,::2]` means k index 1 wali nhi chaye ha 3d mai, phr jo baki ayien un k andr b row 1 and coumn 1 nhi chaye ha baki sb ly ao


### 1D

In [78]:
### 1D arrays
np.random.seed(0)
array = np.random.randint(1, 20, 20)

print(array)
print(array[1])
print(array[5])

[13 16  1  4  4  8 10 19  5  7 13  2  7  8 15 18  6 14  9 10]
16
8


### 2D

In [81]:
np.random.seed(0)
array=np.random.randint(1,20,(6,7))

print(array)
print("------------------------------")
print(array[1,4])
print("------------------------------")
print(array[5,4])

[[13 16  1  4  4  8 10]
 [19  5  7 13  2  7  8]
 [15 18  6 14  9 10 17]
 [ 6 16 16  1 19  4 18]
 [15  8  1  2 10  1 11]
 [ 4 12 19  3  1  1  5]]
------------------------------
2
------------------------------
1


### 3D

In [105]:
np.random.seed(0)
array = np.random.randint(1, 20, (2, 3, 3))

print(array)
print("------------------------------")
print(array[1, 1, 2])
print("------------------------------")
print(array[::2,::2,::2])

[[[13 16  1]
  [ 4  4  8]
  [10 19  5]]

 [[ 7 13  2]
  [ 7  8 15]
  [18  6 14]]]
------------------------------
15
------------------------------
[[[13  1]
  [10  5]]]


## Use negative indexing.

### 1D

In [85]:
### 1D arrays
np.random.seed(0)
array = np.random.randint(1, 20, 20)

print(array)
print(array[-1])
print(array[-15])

[13 16  1  4  4  8 10 19  5  7 13  2  7  8 15 18  6 14  9 10]
10
8


### 2D

In [86]:
np.random.seed(0)
array=np.random.randint(1,20,(6,7))

print(array)
print("------------------------------")
print(array[-2,-2])
print("------------------------------")
print(array[-5,-6])

[[13 16  1  4  4  8 10]
 [19  5  7 13  2  7  8]
 [15 18  6 14  9 10 17]
 [ 6 16 16  1 19  4 18]
 [15  8  1  2 10  1 11]
 [ 4 12 19  3  1  1  5]]
------------------------------
1
------------------------------
5


### 3D

In [87]:
### 3D
np.random.seed(0)
array = np.random.randint(1, 20, (2, 3, 3))

print(array)
print("------------------------------")
print(array[-2, -3, -1])
print("------------------------------")

[[[13 16  1]
  [ 4  4  8]
  [10 19  5]]

 [[ 7 13  2]
  [ 7  8 15]
  [18  6 14]]]
------------------------------
1
------------------------------


# Boolean Masking

## Filter values in arrays using conditions.

In [96]:

np.random.seed(0)
array = np.random.randint(1, 20, 20)

print(array)

mask=(array%2==0)
print("-----------------------------------------------")
print(array[mask])


[13 16  1  4  4  8 10 19  5  7 13  2  7  8 15 18  6 14  9 10]
-----------------------------------------------
[16  4  4  8 10  2  8 18  6 14 10]


In [97]:
array=np.random.randn(6,4)
mask=(array>0)
print(array)
print("-----------------------------------------------")
print(array[mask])

[[-1.27814912  1.43737068 -0.07770457  1.08963016]
 [ 0.09654267  1.41866711  1.16827314  0.94718595]
 [ 1.08548703  2.38222445 -0.40602374  0.26644534]
 [-1.35571372 -0.11410253 -0.84423086  0.70564081]
 [-0.39878617 -0.82719653 -0.4157447  -0.52451219]
 [ 0.81310127 -0.22925063  2.16171737 -0.95693143]]
-----------------------------------------------
[1.43737068 1.08963016 0.09654267 1.41866711 1.16827314 0.94718595
 1.08548703 2.38222445 0.26644534 0.70564081 0.81310127 2.16171737]


In [98]:
array=np.random.randn(2,2,2)
mask=(array>0)
print(array)
print("-----------------------------------------------")
print(array[mask])

[[[ 0.06731083  0.20649884]
  [-0.45688133 -1.05997576]]

 [[ 0.61495732  1.42966077]
  [-0.21195226 -0.08033726]]]
-----------------------------------------------
[0.06731083 0.20649884 0.61495732 1.42966077]


## Combine multiple conditions with & (and), | (or).

In [101]:
np.random.seed(0)
array = np.random.randint(1, 20, 20)

print(array)

mask=(((array%2==0)|(array%3==0)) & (array>10))
print("-----------------------------------------------")
print(array[mask])

[13 16  1  4  4  8 10 19  5  7 13  2  7  8 15 18  6 14  9 10]
-----------------------------------------------
[16 15 18 14]


## Count and sum filtered elements.

In [103]:
np.random.seed(0)
array = np.random.randint(1, 20, 20)

print(array)

mask=(((array%2==0)|(array%3==0)) & (array>10))
print("-----------------------------------------------")
print(array[mask])
print(np.count_nonzero(array[mask]))
print(np.sum(array[mask]))


[13 16  1  4  4  8 10 19  5  7 13  2  7  8 15 18  6 14  9 10]
-----------------------------------------------
[16 15 18 14]
4
63


# Array Math & Broadcasting

## Perform element-wise operations (+, -, *, /, **, %).

In [111]:
np.random.seed(0)
array = np.random.randint(10, 20, 10)
array_2 = np.random.randint(1, 10, 10)


print(array)
print("-----------------------------------------------")
print(array_2)
print("-----------------------------------------------")
print("* operator= ",array*array_2)
print("-----------------------------------------------")
print("+ operator= ",array+array_2)
print("-----------------------------------------------")
print("- operator= ",array-array_2)
print("-----------------------------------------------")
print("/ operator= ",array/array_2)
print("-----------------------------------------------")
print("** operator= ",array**array_2)
print("-----------------------------------------------")
print("% operator= ",array%array_2)

[15 10 13 13 17 19 13 15 12 14]
-----------------------------------------------
[8 7 9 9 2 7 8 8 9 2]
-----------------------------------------------
* operator=  [120  70 117 117  34 133 104 120 108  28]
-----------------------------------------------
+ operator=  [23 17 22 22 19 26 21 23 21 16]
-----------------------------------------------
- operator=  [ 7  3  4  4 15 12  5  7  3 12]
-----------------------------------------------
/ operator=  [1.875      1.42857143 1.44444444 1.44444444 8.5        2.71428571
 1.625      1.875      1.33333333 7.        ]
-----------------------------------------------
** operator=  [ 2562890625    10000000 10604499373 10604499373         289   893871739
   815730721  2562890625  5159780352         196]
-----------------------------------------------
% operator=  [7 3 4 4 1 5 5 7 3 0]


### 2D

In [120]:
np.random.seed(0)
array = np.random.randint(5, 10, (3,2))
array_2 = np.random.randint(1, 5, (3,2))


print(array)
print("-----------------------------------------------")
print(array_2)
print("-----------------------------------------------")
print("* operator= ",array*array_2)
print("-----------------------------------------------")
print("+ operator= ",array+array_2)
print("-----------------------------------------------")
print("- operator= ",array-array_2)
print("-----------------------------------------------")
print("/ operator= ",array/array_2)
print("-----------------------------------------------")
print("** operator= ",array**array_2)
print("-----------------------------------------------")
print("% operator= ",array%array_2)

[[9 5]
 [8 8]
 [8 6]]
-----------------------------------------------
[4 2]
-----------------------------------------------
* operator=  [[36 10]
 [32 16]
 [32 12]]
-----------------------------------------------
+ operator=  [[13  7]
 [12 10]
 [12  8]]
-----------------------------------------------
- operator=  [[5 3]
 [4 6]
 [4 4]]
-----------------------------------------------
/ operator=  [[2.25 2.5 ]
 [2.   4.  ]
 [2.   3.  ]]
-----------------------------------------------
** operator=  [[6561   25]
 [4096   64]
 [4096   36]]
-----------------------------------------------
% operator=  [[1 1]
 [0 0]
 [0 0]]


### 3D

In [126]:
np.random.seed(0)
array = np.random.randint(5, 10, (2,3,3))
array_2 = np.random.randint(1, 5, (2,3,3))


print(array)
print("-----------------------------------------------")
print(array_2)
print("-----------------------------------------------")
print("* operator= ",array*array_2)
print("-----------------------------------------------")
print("+ operator= ",array+array_2)
print("-----------------------------------------------")
print("- operator= ",array-array_2)
print("-----------------------------------------------")
print("/ operator= ",array/array_2)
print("-----------------------------------------------")
print("** operator= ",array**array_2)
print("-----------------------------------------------")
print("% operator= ",array%array_2)

[[[9 5 8]
  [8 8 6]
  [8 7 9]]

 [[5 5 9]
  [7 6 5]
  [6 6 5]]]
-----------------------------------------------
3
-----------------------------------------------
* operator=  [[[27 15 24]
  [24 24 18]
  [24 21 27]]

 [[15 15 27]
  [21 18 15]
  [18 18 15]]]
-----------------------------------------------
+ operator=  [[[12  8 11]
  [11 11  9]
  [11 10 12]]

 [[ 8  8 12]
  [10  9  8]
  [ 9  9  8]]]
-----------------------------------------------
- operator=  [[[6 2 5]
  [5 5 3]
  [5 4 6]]

 [[2 2 6]
  [4 3 2]
  [3 3 2]]]
-----------------------------------------------
/ operator=  [[[3.         1.66666667 2.66666667]
  [2.66666667 2.66666667 2.        ]
  [2.66666667 2.33333333 3.        ]]

 [[1.66666667 1.66666667 3.        ]
  [2.33333333 2.         1.66666667]
  [2.         2.         1.66666667]]]
-----------------------------------------------
** operator=  [[[729 125 512]
  [512 512 216]
  [512 343 729]]

 [[125 125 729]
  [343 216 125]
  [216 216 125]]]
--------------------------

## Use broadcasting to add/subtract scalar to/from arrays.

### 2D
if you wanna broadcast with a fellow 2D one of the array should have either one column or one row as 1 but that still doesnt mean it will always broadcast like in example think

array1
```
[[9 5]
 [8 8]
 [8 6]]
```

array2
```
[[4]
 [2]]
```

now numpy can try ti broadcast the second array as
```
[[4,4]
 [4,4]]
```

but still one row is less so not possible

also for 2d you can use any 1D array shape of no of columns to broadcast


In [140]:
np.random.seed(0)
array = np.random.randint(5, 10, (3,2))
array_2 = np.random.randint(1, 5, ())


print(array)
print("-----------------------------------------------")
print(array_2)
print("-----------------------------------------------")
print("* operator= ",array*array_2)
print("-----------------------------------------------")
print("+ operator= ",array+array_2)
print("-----------------------------------------------")
print("- operator= ",array-array_2)
print("-----------------------------------------------")
print("/ operator= ",array/array_2)
print("-----------------------------------------------")
print("** operator= ",array**array_2)
print("-----------------------------------------------")
print("% operator= ",array%array_2)

[[9 5]
 [8 8]
 [8 6]]
-----------------------------------------------
[4 2]
-----------------------------------------------
* operator=  [[36 10]
 [32 16]
 [32 12]]
-----------------------------------------------
+ operator=  [[13  7]
 [12 10]
 [12  8]]
-----------------------------------------------
- operator=  [[5 3]
 [4 6]
 [4 4]]
-----------------------------------------------
/ operator=  [[2.25 2.5 ]
 [2.   4.  ]
 [2.   3.  ]]
-----------------------------------------------
** operator=  [[6561   25]
 [4096   64]
 [4096   36]]
-----------------------------------------------
% operator=  [[1 1]
 [0 0]
 [0 0]]


In [134]:
np.random.seed(0)
array = np.random.randint(5, 10, (3,2))
array_2 = np.random.randint(1, 5, (2,1))


print(array)
print("-----------------------------------------------")
print(array_2)
print("-----------------------------------------------")
print("* operator= ",array*array_2)
print("-----------------------------------------------")
print("+ operator= ",array+array_2)
print("-----------------------------------------------")
print("- operator= ",array-array_2)
print("-----------------------------------------------")
print("/ operator= ",array/array_2)
print("-----------------------------------------------")
print("** operator= ",array**array_2)
print("-----------------------------------------------")
print("% operator= ",array%array_2)

[[9 5]
 [8 8]
 [8 6]]
-----------------------------------------------
[[4]
 [2]]
-----------------------------------------------


ValueError: operands could not be broadcast together with shapes (3,2) (2,1) 

### 3D array

for the third vector it should either be 1 or same for both and other than that same rules as 2d


In [146]:
np.random.seed(0)
array = np.random.randint(5, 10, (2,3,3))
array_2 = np.random.randint(1, 5, (2,1,3))


print(array)
print("-----------------------------------------------")
print(array_2)
print("-----------------------------------------------")
print("* operator= ",array*array_2)
print("-----------------------------------------------")
print("+ operator= ",array+array_2)
print("-----------------------------------------------")
print("- operator= ",array-array_2)
print("-----------------------------------------------")
print("/ operator= ",array/array_2)
print("-----------------------------------------------")
print("** operator= ",array**array_2)
print("-----------------------------------------------")
print("% operator= ",array%array_2)

[[[9 5 8]
  [8 8 6]
  [8 7 9]]

 [[5 5 9]
  [7 6 5]
  [6 6 5]]]
-----------------------------------------------
[[[2 1 4]]

 [[1 4 2]]]
-----------------------------------------------
* operator=  [[[18  5 32]
  [16  8 24]
  [16  7 36]]

 [[ 5 20 18]
  [ 7 24 10]
  [ 6 24 10]]]
-----------------------------------------------
+ operator=  [[[11  6 12]
  [10  9 10]
  [10  8 13]]

 [[ 6  9 11]
  [ 8 10  7]
  [ 7 10  7]]]
-----------------------------------------------
- operator=  [[[7 4 4]
  [6 7 2]
  [6 6 5]]

 [[4 1 7]
  [6 2 3]
  [5 2 3]]]
-----------------------------------------------
/ operator=  [[[4.5  5.   2.  ]
  [4.   8.   1.5 ]
  [4.   7.   2.25]]

 [[5.   1.25 4.5 ]
  [7.   1.5  2.5 ]
  [6.   1.5  2.5 ]]]
-----------------------------------------------
** operator=  [[[  81    5 4096]
  [  64    8 1296]
  [  64    7 6561]]

 [[   5  625   81]
  [   7 1296   25]
  [   6 1296   25]]]
-----------------------------------------------
% operator=  [[[1 0 0]
  [0 0 2]
  [0 0 1]]

 