In [45]:
import numpy as np
import matplotlib.pyplot as plt
from matplotlib_inline.backend_inline import show

%matplotlib inline


# Array Creation and Properties

 ## 1) Create 1D, 2D, and 3D arrays using np.array, np.zeros, np.ones, and np.full.

### 1D Array
why not use pythons own array ?
because numpy gives special functions like say you can do element wise multiplication of numpy array as (a*b) but cant do the same for python arrays

**dattype of all elements in the array would be same**

say you have `np.array([1,2,3.6])` datatype=Float

`np.array([1,2,3.6,"Bilal"])` numpy will convert all the values to datatype string


In [46]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

print(x * y)


[ 4 10 18]


In [47]:
ones_1d = np.ones(9, dtype=int)
zeros_1d = np.zeros(9)
full_1d = np.full(9, 2)  # shape =1d array of length 9 and 2 is the value to be filled

print("Ones Array ", ones_1d, "\nZeros Array ", zeros_1d, "\nFull Array ", full_1d)

Ones Array  [1 1 1 1 1 1 1 1 1] 
Zeros Array  [0. 0. 0. 0. 0. 0. 0. 0. 0.] 
Full Array  [2 2 2 2 2 2 2 2 2]


### 2D Array

In [48]:
simple_2d = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

ones_2d = np.ones((3, 3), dtype=int)
zeros_2d = np.zeros((4, 3))
full_2d = np.full((4, 5), 2)  # shape =(4 x 5)and 2 is the value to be filled

print("Simple 2D \n", simple_2d, "\nOnes Array \n", ones_2d, "\nZeros Array \n", zeros_2d, "\nFull Array\n", full_2d)

Simple 2D 
 [[1 2 3]
 [4 5 6]
 [7 8 9]] 
Ones Array 
 [[1 1 1]
 [1 1 1]
 [1 1 1]] 
Zeros Array 
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]] 
Full Array
 [[2 2 2 2 2]
 [2 2 2 2 2]
 [2 2 2 2 2]
 [2 2 2 2 2]]


# 3D Array

In [49]:
simple_3d = np.array([  # 2x 2 x3 meaning there are 2 2d arrays of shape(2x3)
    [
        [1, 2, 3],
        [4, 5, 6]
    ],

    [

        [7, 8, 9],
        [10, 11, 12]
    ],

])

ones_3d = np.ones((2, 2, 3), dtype=int)
zeros_3d = np.zeros((2, 2, 3))
full_3d = np.full((2, 2, 3), 2)  # shape =(2 x 2 x 3) and 2 is the value to be filled

print("Simple 3D \n", simple_3d, "\nOnes Array \n", ones_3d, "\nZeros Array \n", zeros_3d, "\nFull Array\n", full_3d)

Simple 3D 
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]] 
Ones Array 
 [[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]] 
Zeros Array 
 [[[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]] 
Full Array
 [[[2 2 2]
  [2 2 2]]

 [[2 2 2]
  [2 2 2]]]


## 2) Use np.arange() and np.linspace() to create arrays with evenly spaced values.

### np.arange()
this functions return an array in range given with the required steps

`np.arange(from,to,step)`

default from is 0
default step is 1

In [50]:
arange_array = np.arange(1, 5.)

arange_array_2 = np.arange(5)

arange_array_3 = np.arange(1, 10.1, 2)  # from 1 to 10 as 10.1 not included with step of 2

print(arange_array)
print(arange_array_2)
print(arange_array_3)

arange_array.dtype

[1. 2. 3. 4.]
[0 1 2 3 4]
[1. 3. 5. 7. 9.]


dtype('float64')

### np.linspace()

used to generate n number of numbers between 2 values in a linear way like difference is same

`np.linspace(from, to, how_many_numbers)`

In [51]:
linspace_usage = np.linspace(1, 100, 6)
print(linspace_usage)

[  1.   20.8  40.6  60.4  80.2 100. ]


## 3) Check array properties: .ndim, .shape, .size, .dtype.


### ndim
Returns the number of dimensions of the array.

In [52]:
print(simple_2d.ndim)
print(simple_3d.ndim)

2
3


### .shape
returns the shape along with dimensions

In [53]:
print(simple_2d.shape)
print(simple_3d.shape)

(3, 3)
(2, 2, 3)


### .size

return size like a 2x3 has size 6

In [55]:
print(simple_2d.shape)
print(simple_3d.size)

(3, 3)
12


### dtype
returns the data type of the array

In [ ]:
print(simple_2d.dtype)
print(simple_3d.dtype)

# Reshape and Flatten

## Reshape arrays using .reshape() and .flatten().

### .reshape()
reshape allow us to reshape our array but while reshaping form less dimension to hogher dimension we need to be careful that the size is similar or else there will be an error

also we can use the syntax `np.reshape(-1,1)` which means 1 column and as many rows as needed or available
`np.reshape(1,-1)`  which means 1 row and as many rows as needed

rather than doing `np.reshape(size,1)`

order="F" means columns wise by default it is row wise

In [ ]:
array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

array_2d = array.reshape((4, 3), order="F")

array_3d = array.reshape((2, 2, 3))

print(array_2d, "\n \n \n 3d \n", array_3d)

In [ ]:
single_column = array_3d.reshape((-1, 1))
two_column = array_3d.reshape((-1, 2))

print(single_column, "\n \n two column\n", two_column)

In [ ]:
single_row = array_3d.reshape((1, -1))
two_row = array_3d.reshape((2, -1))

print(single_row, "\n \n two row\n", two_row)


### flatten()
flatten function makes adeep copy meaning like changing the new y variable wont affect the values in original x
and it converts higher dimensional arrays into a 1D array

In [ ]:
y1 = array_3d.flatten()
y2 = array_2d.flatten()

y1[0] = 0

print("Original\n", array_3d, "\n \n y1\n \n", y1, "\n \n y2\n \n", y2)

# Random Numbers

## Use np.random.randint(), np.random.rand(), np.random.randn(), and np.random.seed() to create random arrays.

### np.random.randint()
return random int numbers between a certain like boundary for a specific shape

In [ ]:
random_array = np.random.randint(0, 10, size=(2, 3))
print(random_array)

### np.random.rand()

return random number between 0 and 1 and no negative values

In [ ]:
random_array = np.random.rand(2, 3)
print(random_array)

### np.random.randn()
return random numbers between0 and 1 also includes negative values

In [57]:
random_array = np.random.randn(2, 3)
print(random_array)

[[ 0.86183705 -0.1812793   0.75660762]
 [-0.11416941  0.58775665 -0.09282735]]


### np.random.shuffle()
shuffles the values in place , does not return anything

if you want to return anything use `np.random.permutation(x)`

In [ ]:
np.random.shuffle(array_2d)
print(array_2d)

### np.random.seed()
allows us to get the same value while random valuing things as long as we use the same number in the parenthesis of seed

In [ ]:
np.random.seed(2)
random_array = np.random.randn(2, 3)
print(random_array)

### np.random.normal

`np.random.normal(100,15,20)`

what this means is that most values are close to 100, where the second argument 15 means how big of a jump can we have a smaller value means not that big of a jump and a higher value means a bigger jump

In [ ]:
x = np.random.normal(100, 15, 20)
print(x)

## Use .mean(), .min(), .max(), .argmin(), .argmax() to summarize data.

## .mean
calculates the mean/average of the data

In [ ]:
array = np.array([1, 2, 3, 4, 5, 6, 7])

array2 = np.array([
    [1, 2, 3, 4, 5],
    [6, 7, 8, 9, 10],
    [11, 12, 13, 14, 15]
])

mean_1d = np.mean(array)

mean_2d = np.mean(array2)
mean_2d_columns = np.mean(array2, axis=1)

print(mean_1d, "\n", mean_2d, "\n", mean_2d_columns)

### .min() & .max()
get the minimum and maximum value respectively

In [ ]:
array = np.array([1, 2, 3, 4, 5, 6, 7])

array2 = np.array([
    [0, 2, 3, 4, 5],
    [6, 7, 8, 9, 10],
    [11, 12, 13, 14, 121]
])

print("Minimum\n", np.min(array), "\n", np.min(array2))
print("Maximum\n", np.max(array), "\n", np.max(array2))

### argmin() & argmax()
returns the indent of the minimum and maximum value

In [ ]:
array = np.array([1, 2, 3, 4, 5, 6, 7])

array2 = np.array([
    [0, 2, 3, 4, 5],
    [6, 7, 8, 9, 10],
    [11, 12, 13, 14, 121]
])

print("Minimum at index\n", np.argmin(array), "\n", np.argmin(array2))
print("Maximum at index\n", np.argmax(array), "\n", np.argmax(array2))

#  Indexing and Slicing

## Index and slice 1D and 2D arrays.


### 1D arrays

In [ ]:
np.random.seed(0)
array = np.random.randint(1, 20, 20)

print(array[1:4])
print(array[5:])


### 2D arrays

In [ ]:
np.random.seed(0)
array = np.random.randint(1, 20, (6, 7))

print(array)
print("------------------------------")
print(array[1:4, :])
print("------------------------------")
print(array[5:, 3:])

### 3D arrays

In [ ]:

np.random.seed(0)
array = np.random.randint(1, 20, (2, 3, 3))

print(array)
print("------------------------------")
print(array[:3, 1, :])
print("------------------------------")


## Access specific rows, columns, and elements.

`array[::2]` means k 2 sh pehly wali index mtlb index 1 wali cheez nahi chaye baki sb chaye ha

`array[::2,::2,::2]` means k index 1 wali nhi chaye ha 3d mai, phr jo baki ayien un k andr b row 1 and coumn 1 nhi chaye ha baki sb ly ao


### 1D

In [ ]:
### 1D arrays
np.random.seed(0)
array = np.random.randint(1, 20, 20)

print(array)
print(array[1])
print(array[5])

### 2D

In [ ]:
np.random.seed(0)
array = np.random.randint(1, 20, (6, 7))

print(array)
print("------------------------------")
print(array[1, 4])
print("------------------------------")
print(array[5, 4])

### 3D

In [ ]:
np.random.seed(0)
array = np.random.randint(1, 20, (2, 3, 3))

print(array)
print("------------------------------")
print(array[1, 1, 2])
print("------------------------------")
print(array[::2, ::2, ::2])

## Use negative indexing.

### 1D

In [ ]:
### 1D arrays
np.random.seed(0)
array = np.random.randint(1, 20, 20)

print(array)
print(array[-1])
print(array[-15])

### 2D

In [ ]:
np.random.seed(0)
array = np.random.randint(1, 20, (6, 7))

print(array)
print("------------------------------")
print(array[-2, -2])
print("------------------------------")
print(array[-5, -6])

### 3D

In [ ]:
### 3D
np.random.seed(0)
array = np.random.randint(1, 20, (2, 3, 3))

print(array)
print("------------------------------")
print(array[-2, -3, -1])
print("------------------------------")

# Boolean Masking

## Filter values in arrays using conditions.

In [ ]:

np.random.seed(0)
array = np.random.randint(1, 20, 20)

print(array)

mask = (array % 2 == 0)
print("-----------------------------------------------")
print(array[mask])


In [ ]:
array = np.random.randn(6, 4)
mask = (array > 0)
print(array)
print("-----------------------------------------------")
print(array[mask])

In [ ]:
array = np.random.randn(2, 2, 2)
mask = (array > 0)
print(array)
print("-----------------------------------------------")
print(array[mask])

## Combine multiple conditions with & (and), | (or).

In [ ]:
np.random.seed(0)
array = np.random.randint(1, 20, 20)

print(array)

mask = (((array % 2 == 0) | (array % 3 == 0)) & (array > 10))
print("-----------------------------------------------")
print(array[mask])

## Count and sum filtered elements.

In [ ]:
np.random.seed(0)
array = np.random.randint(1, 20, 20)

print(array)

mask = (((array % 2 == 0) | (array % 3 == 0)) & (array > 10))
print("-----------------------------------------------")
print(array[mask])
print(np.count_nonzero(array[mask]))
print(np.sum(array[mask]))


# Array Math & Broadcasting

## Perform element-wise operations (+, -, *, /, **, %).

In [ ]:
np.random.seed(0)
array = np.random.randint(10, 20, 10)
array_2 = np.random.randint(1, 10, 10)

print(array)
print("-----------------------------------------------")
print(array_2)
print("-----------------------------------------------")
print("* operator= ", array * array_2)
print("-----------------------------------------------")
print("+ operator= ", array + array_2)
print("-----------------------------------------------")
print("- operator= ", array - array_2)
print("-----------------------------------------------")
print("/ operator= ", array / array_2)
print("-----------------------------------------------")
print("** operator= ", array ** array_2)
print("-----------------------------------------------")
print("% operator= ", array % array_2)

### 2D

In [ ]:
np.random.seed(0)
array = np.random.randint(5, 10, (3, 2))
array_2 = np.random.randint(1, 5, (3, 2))

print(array)
print("-----------------------------------------------")
print(array_2)
print("-----------------------------------------------")
print("* operator= ", array * array_2)
print("-----------------------------------------------")
print("+ operator= ", array + array_2)
print("-----------------------------------------------")
print("- operator= ", array - array_2)
print("-----------------------------------------------")
print("/ operator= ", array / array_2)
print("-----------------------------------------------")
print("** operator= ", array ** array_2)
print("-----------------------------------------------")
print("% operator= ", array % array_2)

### 3D

In [ ]:
np.random.seed(0)
array = np.random.randint(5, 10, (2, 3, 3))
array_2 = np.random.randint(1, 5, (2, 3, 3))

print(array)
print("-----------------------------------------------")
print(array_2)
print("-----------------------------------------------")
print("* operator= ", array * array_2)
print("-----------------------------------------------")
print("+ operator= ", array + array_2)
print("-----------------------------------------------")
print("- operator= ", array - array_2)
print("-----------------------------------------------")
print("/ operator= ", array / array_2)
print("-----------------------------------------------")
print("** operator= ", array ** array_2)
print("-----------------------------------------------")
print("% operator= ", array % array_2)

## Use broadcasting to add/subtract scalar to/from arrays.

### 2D
if you wanna broadcast with a fellow 2D one of the array should have either one column or one row as 1 but that still doesnt mean it will always broadcast like in example think

array1
```
[[9 5]
 [8 8]
 [8 6]]
```

array2
```
[[4]
 [2]]
```

now numpy can try ti broadcast the second array as
```
[[4,4]
 [4,4]]
```

but still one row is less so not possible

also for 2d you can use any 1D array shape of no of columns to broadcast


In [ ]:
np.random.seed(0)
array = np.random.randint(5, 10, (3, 2))
array_2 = np.random.randint(1, 5, ())

print(array)
print("-----------------------------------------------")
print(array_2)
print("-----------------------------------------------")
print("* operator= ", array * array_2)
print("-----------------------------------------------")
print("+ operator= ", array + array_2)
print("-----------------------------------------------")
print("- operator= ", array - array_2)
print("-----------------------------------------------")
print("/ operator= ", array / array_2)
print("-----------------------------------------------")
print("** operator= ", array ** array_2)
print("-----------------------------------------------")
print("% operator= ", array % array_2)

In [ ]:
np.random.seed(0)
array = np.random.randint(5, 10, (3, 2))
array_2 = np.random.randint(1, 5, (2, 1))

print(array)
print("-----------------------------------------------")
print(array_2)
print("-----------------------------------------------")
print("* operator= ", array * array_2)
print("-----------------------------------------------")
print("+ operator= ", array + array_2)
print("-----------------------------------------------")
print("- operator= ", array - array_2)
print("-----------------------------------------------")
print("/ operator= ", array / array_2)
print("-----------------------------------------------")
print("** operator= ", array ** array_2)
print("-----------------------------------------------")
print("% operator= ", array % array_2)

### 3D array

for the third vector it should either be 1 or same for both and other than that same rules as 2d


In [ ]:
np.random.seed(0)
array = np.random.randint(5, 10, (2, 3, 3))
array_2 = np.random.randint(1, 5, (2, 1, 3))

print(array)
print("-----------------------------------------------")
print(array_2)
print("-----------------------------------------------")
print("* operator= ", array * array_2)
print("-----------------------------------------------")
print("+ operator= ", array + array_2)
print("-----------------------------------------------")
print("- operator= ", array - array_2)
print("-----------------------------------------------")
print("/ operator= ", array / array_2)
print("-----------------------------------------------")
print("** operator= ", array ** array_2)
print("-----------------------------------------------")
print("% operator= ", array % array_2)

## Use np.sum(), np.prod(), np.mean(), etc.

### np.sum()

In [ ]:
np.random.seed(0)
array = np.random.randint(5, 10, (2, 3, 3))
print(np.sum(array))


### np.prod
takes prod of all elements or elements of columns or rows

In [ ]:
np.random.seed(0)
array = np.random.randint(5, 10, (3, 3))

print(array)
print(np.prod(array, axis=0))

### np.mean
Takes mean/average

In [ ]:
np.random.seed(0)
array = np.random.randint(5, 10, (3, 3))

print(array)
print(np.mean(array, axis=0))

# Plotting with Matplotlib

## Create line plots using plt.plot()
When to use

When data changes over time

To see trends

X-axis → time (days)

Y-axis → values (sales)

In [ ]:
x = np.array([1, 3, 4, 2, 7, 5, 9, 6, 8, 10])
y = np.arange(1, 5.6, 0.5)

print(x, "\n", y, "\n")
plt.plot(x, y, label='simple line')
plt.plot(y, x, label='reverse line')
plt.xlabel('x-axis')
plt.ylabel('y-axis')
plt.legend()
plt.title("Starting off")

## Create bar plots using plt.bar().
To compare categories

Data is discrete

ach bar = one category

Height = value

Bars have gaps

Think: number of students per class, sales per brand

In [ ]:
x = np.array(["A", "B", "C", "D", "E"])
y = np.arange(1, 5.1, 1)

print(x, "\n", y, "\n")
plt.bar(x, y)
plt.xlabel('x-axis')
plt.ylabel('y-axis')
plt.title("Starting off")

## Create scatter plots using plt.scatter().
To see relationship between two numbers

To find patterns or clusters

What it shows

Each dot = one observation

Shows if more hours → better marks

No connecting lines

In [ ]:

x = np.array([1, 3, 4, 2, 7, 5, 9, 6, 8, 10])
y = np.arange(1, 5.6, 0.5)

print(x, "\n", y, "\n")
plt.scatter(x, y)
plt.xlabel('x-axis')
plt.ylabel('y-axis')
plt.title("Starting off")
plt.grid()

## Create histogram plots using plt.hist().
Imagine exam scores of 100 students:

23, 45, 67, 68, 70, 71, 72, 85, 90, ...


Instead of listing all numbers, we group them:

Score Range	Students
0–10	1
10–20	2
20–30	5
30–40	10
40–50	20

A histogram draws this visually.

How a histogram shows data

X-axis → value ranges (called bins)

Y-axis → how many values fall in each range (frequency)

In [ ]:


data = np.random.normal(50, 10, 1000)

plt.hist(data, bins=20, edgecolor="black")


# Subplots and Multiple Figures

## Use plt.subplot() to create multiple plots in one figure.

you can basically made more than one like plots in the same graph
the subplot(2,2) basically gives you 2 rows and 2 column so basically 4 graphs

In [ ]:
fig, axes = plt.subplots(2, 2)

x = np.random.randint(1, 10, 5)

data = np.random.normal(50, 10, 1000)

axes[0, 0].plot(x, x * 2)
axes[0, 0].set_title("first one")

axes[0, 1].hist(data, bins=20, color="red", edgecolor="black")
axes[0, 1].set_title("second one")

axes[1, 0].bar(["A", "B", "C", "D", "E"], x)
axes[1, 0].set_title("third one")

axes[1, 1].scatter(x, x - 3)
axes[1, 1].set_title("fourth one")
plt.tight_layout()  #insures no overlapping between charts
plt.savefig("/Users/Bilal/Desktop/charts/savesubplots")

