In [2]:
import numpy as np
from numpy.ma.core import shape
from numpy.matlib import zeros

# Array Creation and Properties

 ## 1) Create 1D, 2D, and 3D arrays using np.array, np.zeros, np.ones, and np.full.

### 1D Array
why not use pythons own array ?
because numpy gives special functions like say you can do element wise multiplication of numpy array as (a*b) but cant do the same for python arrays

**dattype of all elements in the array would be same**

say you have `np.array([1,2,3.6])` datatype=Float

`np.array([1,2,3.6,"Bilal"])` numpy will convert all the values to datatype string


In [3]:
x=np.array([1,2,3])
y=np.array([4,5,6])

print(x*y)


[ 4 10 18]


In [5]:
ones_1d=np.ones(9,dtype=int)
zeros_1d=np.zeros(9)
full_1d=np.full(9,2)   # shape =1d array of length 9 and 2 is the value to be filled

print("Ones Array ",ones_1d,"\nZeros Array ",zeros_1d,"\nFull Array ",full_1d)

Ones Array  [1 1 1 1 1 1 1 1 1] 
Zeros Array  [0. 0. 0. 0. 0. 0. 0. 0. 0.] 
Full Array  [2 2 2 2 2 2 2 2 2]


### 2D Array

In [7]:
simple_2d=np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

ones_2d=np.ones((3,3),dtype=int)
zeros_2d=np.zeros((4,3))
full_2d=np.full((4,5),2)   # shape =(4 x 5)and 2 is the value to be filled


print("Simple 2D \n",simple_2d,"\nOnes Array \n",ones_2d,"\nZeros Array \n",zeros_2d,"\nFull Array\n",full_2d)

Simple 2D 
 [[1 2 3]
 [4 5 6]
 [7 8 9]] 
Ones Array 
 [[1 1 1]
 [1 1 1]
 [1 1 1]] 
Zeros Array 
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]] 
Full Array
 [[2 2 2 2 2]
 [2 2 2 2 2]
 [2 2 2 2 2]
 [2 2 2 2 2]]


# 3D Array

In [8]:
simple_3d=np.array([          # 2x 2 x3 meaning there are 2 2d arrays of shape(2x3)
    [
        [1,2,3],
        [4,5,6]
    ],

    [
        [7,8,9],
        [10,11,12]
    ],

])

ones_3d=np.ones((2,2,3),dtype=int)
zeros_3d=np.zeros((2,2,3))
full_3d=np.full((2,2,3),2)   # shape =(2 x 2 x 3) and 2 is the value to be filled


print("Simple 3D \n",simple_3d,"\nOnes Array \n",ones_3d,"\nZeros Array \n",zeros_3d,"\nFull Array\n",full_3d)

Simple 2D 
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]] 
Ones Array 
 [[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]] 
Zeros Array 
 [[[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]] 
Full Array
 [[[2 2 2]
  [2 2 2]]

 [[2 2 2]
  [2 2 2]]]


## 2) Use np.arange() and np.linspace() to create arrays with evenly spaced values.

### np.arange()
this functions return an array in range given with the required steps

`np.arange(from,to,step)`

default from is 0
default step is 1

In [11]:
arange_array= np.arange(1,5,dtype=int)

arange_array_2=np.arange(5)

arange_array_3 = np.arange(1,10.1,2) # from 1 to 10 as 10.1 not included with step of 2

print(arange_array)
print(arange_array_2)
print(arange_array_3)

[1 2 3 4]
[0 1 2 3 4]
[1. 3. 5. 7. 9.]


### np.linspace()

used to generate n number of numbers between 2 values in a linear way like difference is same

`np.linspace(from, to, how_many_numbers)`

In [12]:
linspace_usage= np.linspace(1,100,6)
print(linspace_usage)

[  1.   20.8  40.6  60.4  80.2 100. ]


## 3) Check array properties: .ndim, .shape, .size, .dtype.


### ndim
Returns the number of dimensions of the array.

In [15]:
print(simple_2d.ndim)
print(simple_3d.ndim)

2
3


### .shape
returns the shape along with dimensions

In [16]:
print(simple_2d.shape)
print(simple_3d.shape)

(3, 3)
(2, 2, 3)


### .size

return size like a 2x3 has size 6

In [17]:
print(simple_2d.size)
print(simple_3d.size)

9
12


### dtype
returns the data type of the array

In [18]:
print(simple_2d.dtype)
print(simple_3d.dtype)

int64
int64


# Reshape and Flatten

## Reshape arrays using .reshape() and .flatten().

### .reshape()
reshape allow us to reshape our array but while reshaping form less dimension to hogher dimension we need to be careful that the size is similar or else there will be an error

also we can use the syntax `np.reshape(-1,1)` which means 1 column and as many rows as needed or available
`np.reshape(1,-1)`  which means 1 row and as many rows as needed

rather than doing `np.reshape(size,1)`

order="F" means columns wise by default it is row wise

In [23]:
array= np.array([1,2,3,4,5,6,7,8,9,10,11,12])

array_2d=array.reshape((4,3),order="F")

array_3d=array.reshape((2,2,3))

print(array_2d,"\n \n \n 3d \n",array_3d)

[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]] 
 
 
 3d 
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [25]:
single_column= array_3d.reshape((-1,1))
two_column = array_3d.reshape((-1,2))

print(single_column,"\n \n two column\n",two_column)

[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]] 
 
 two column
 [[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]


In [26]:
single_row= array_3d.reshape((1,-1))
two_row = array_3d.reshape((2,-1))

print(single_row,"\n \n two row\n",two_row)


[[ 1  2  3  4  5  6  7  8  9 10 11 12]] 
 
 two row
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


### flatten()
flatten function makes adeep copy meaning like changing the new y variable wont affect the values in original x
and it converts higher dimensional arrays into a 1D array

In [27]:
y1= array_3d.flatten()
y2=array_2d.flatten()

y1[0]=0

print("Original\n",array_3d,"\n \n y1\n \n",y1,"\n \n y2\n \n",y2)

Original
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]] 
 
 y1
 
 [ 0  2  3  4  5  6  7  8  9 10 11 12] 
 
 y2
 
 [ 1  5  9  2  6 10  3  7 11  4  8 12]


# Random Numbers

## Use np.random.randint(), np.random.rand(), np.random.randn(), and np.random.seed() to create random arrays.

### np.random.randint()
return random int numbers between a certain like boundary for a specific shape

In [32]:
random_array = np.random.randint(0, 10, size=(2,3))
print(random_array)

[[0 5 1]
 [8 8 0]]


### np.random.rand()

return random number between 0 and 1 and no negative values

In [37]:
random_array = np.random.rand(2,3)
print(random_array)

[[0.43753955 0.70570874 0.93994972]
 [0.53377796 0.226142   0.74684026]]


### np.random.randn()
return random numbers between0 and 1 also includes negative values

In [38]:
random_array = np.random.randn(2,3)
print(random_array)

[[-0.2468163  -0.56113873  0.46424981]
 [-1.50635365 -0.40897557 -0.74665814]]


### np.random.shuffle()
shuffles the values in place , does not return anything

if you want to return anything use `np.random.permutation(x)`

In [51]:
np.random.shuffle(array_2d)
print(array_2d)

[[ 3  7 11]
 [ 2  6 10]
 [ 1  5  9]
 [ 4  8 12]]


### np.random.seed()
allows us to get the same value while random valuing things as long as we use the same number in the parenthesis of seed

In [61]:
np.random.seed(2)
random_array = np.random.randn(2,3)
print(random_array)

[[-0.41675785 -0.05626683 -2.1361961 ]
 [ 1.64027081 -1.79343559 -0.84174737]]
